### PR TITLE
fix crash

### PR DESCRIPTION
**Pull request by Pub4Game**

### CODE REVIEW

**Comment by dterweij** [comment]
Please make a new release or where can I get the phar with the fix?

**Comment by Matthww** [comment]
@dterweij https://transfer.sh/qyW47/killrate-php5.phar 

Here you go :)

**Comment by Matthww** [comment]
@Pub4Game Could you maybe fix Livesign for php7?

**Comment by Pub4Game** [comment]
I'm busy with my own plugin for Nukkit

**Pull request merged**
