### PR TITLE
Added popup when player use a Sign Warp

### PR DESCRIPTION
**Pull request by TonyDroidd**
Is not very important, but it is a nice  detail :)
I tried it, it looks very nice :D

### CODE REVIEW

**Comment by alejandroliu** [comment]
Won't be adding PM1.5 specific features until PM1.5 becomes Generally Available.

**Comment by TonyDroidd** [comment]
ammm.. what?

**Comment by TonyDroidd** [comment]
PM 1.5 is generally avaliable

**Comment by alejandroliu** [comment]
I was referring to PM1.5 becomes the stable version.

I don't have MCPE 0.11.0 beta4 myself, so I can't really test it.

**Comment by TonyDroidd** [comment]
oh, okok, but i tried this, and work fine jaja :D

**Pull request closed without merging**
